# Generated by Django 5.1.2 on 2024-10-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='alumno_inscripcion',
            new_name='curso_inscripcion',
        ),
    ]
