# Generated by Django 5.1.2 on 2024-10-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_rename_alumno_inscripcion_inscripcion_curso_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='username',
            field=models.CharField(default='False', max_length=100),
        ),
    ]
